### ISSUE TITLE
Got exception in fabric8-forge while trying to start pipeline

### ISSUE THREAD

**Issue by andrewscat** [fabric8-launcher/launcher-booster-catalog#157]
Hi,

I am using fabric8 version 4.0.208

When I am trying to run pipeline (but maybe earlier, I'm not sure), I got the exception. It looks as if it's connected to the file `rest-http-secured/wildfly-swarm/redhat/wildfly-swarm-rest-http-secured-redhat.yaml` in branch `next`. As far as I can see, it was replaced recently in master-branch.

```
2018-02-09 10:38:44,431 INFO  [io.openshift.booster.catalog.BoosterCatalogService] (Thread-39) Indexing /tmp/booster-catalog6281128579201572270/rest-http-secured/wildfly-swarm/redhat/wildfly-swarm-rest-http-secured-redhat.yaml ...
2018-02-09 10:38:44,432 SEVERE [io.openshift.booster.catalog.BoosterCatalogService] (Thread-39) Error while indexing: Cannot create property=supportedDeploymentTypes for JavaBean=Booster [id=null, githubRepo=wildfly-swarm-openshiftio-boosters/wfswarm-rest-http-secured-redhat, gitRef=7.0.0-redhat-4, buildProfile=null, description=No description available, boosterDescriptorPath=.openshiftio/booster.yaml, mission=null, runtime=null, version=null, contentPath=null, metadata={}]
 in 'reader', line 1, column 1:
    githubRepo: wildfly-swarm-opensh ...
    ^
Unable to find property 'supportedDeploymentTypes' on class: io.openshift.booster.catalog.Booster
 in 'reader', line 3, column 27:
    supportedDeploymentTypes: zip
                              ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:313)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:190)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:346)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:143)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:129)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:465)
	at io.openshift.booster.catalog.BoosterCatalogService.indexBooster(BoosterCatalogService.java:221)
	at io.openshift.booster.catalog.BoosterCatalogService.access$000(BoosterCatalogService.java:57)
	at io.openshift.booster.catalog.BoosterCatalogService$1.visitFile(BoosterCatalogService.java:152)
	at io.openshift.booster.catalog.BoosterCatalogService$1.visitFile(BoosterCatalogService.java:137)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at io.openshift.booster.catalog.BoosterCatalogService.indexBoosters(BoosterCatalogService.java:136)
	at io.openshift.booster.catalog.BoosterCatalogService.doIndex(BoosterCatalogService.java:115)
	at io.openshift.booster.catalog.BoosterCatalogService.lambda$index$0(BoosterCatalogService.java:98)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'supportedDeploymentTypes' on class: io.openshift.booster.catalog.Booster
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:323)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:241)
	... 18 more

Note: checking out 'f05763b9e4e50b050f72432b619d75e5a7098206'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name
```

The file content:
```
githubRepo: wildfly-swarm-openshiftio-boosters/wfswarm-rest-http-secured-redhat
gitRef: 7.0.0-redhat-4
supportedDeploymentTypes: zip
```

Could you please take a look, maybe it makes sense to update `next` branch as well.

**Comment by quintesse** [comment]
@andrewscat you're using old code, the file format for the catalog has changed. See the new documentation here: https://github.com/fabric8-launcher/launcher-booster-catalog/wiki/HOWTO-Create-a-Booster-Catalog-(RHOAR)

**Comment by gastaldi** [comment]
https://github.com/fabric8io/fabric8-forge is deprecated and was superseded by https://github.com/fabric8-launcher/. That repository must be archived and any references to it removed from the fabric8 project.

**Comment by quintesse** [comment]
If someone wants to fix this they'll have to update the `booster-catalog-service` component to [the latest version](https://search.maven.org/#artifactdetails%7Cio.fabric8.launcher%7Cbooster-catalog-service%7C23%7Cjar). That probably means having to make some code changes because the new version is not entirely backward compatible, but the information it returns still contains the same information, so it shouldn't be too hard.

**Comment by andrewscat** [comment]
I got it, thanks for help, guys.
Is it possible to deploy some kind of stable release of 4.X version without hacking?
And if so, is there a manual for that? We have spent a couple of days trying to make it work, but with no success.

**Comment by gastaldi** [comment]
@andrewscat yes, update the dependency on the `booster-catalog-service` in `fabric8-forge` to `v14` (it's the version that supports this missing property) and that should work. Make sure to use a tagged ref from this repository too

**Comment by andrewscat** [comment]
@gastaldi @quintesse 
Well, I've got one more stupid question.
I haven't found `booster-catalog-service` dependency in pom.xml files in [actual fabric8-forge repo ](https://github.com/fabric8io/fabric8-forge)
Which repo do you mean?
And as I understood, currently it's not enough to play with gofabric8's cli options to install working version, is it?

**Comment by gastaldi** [comment]
It may be a transitive dependency. Make sure that the following version is used in a dependency in fabric8-forge
```xml
   <groupId>io.openshift.launchpad</groupId>
   <artifactId>launchpad-addon</artifactId>
   <version>18</version>
```

**Comment by gastaldi** [comment]
This is the repository that contains it: https://github.com/fabric8io/fabric8-generator it should be archived too

**Comment by gastaldi** [comment]
This line specifically: https://github.com/fabric8io/fabric8-generator/blob/master/pom.xml#L25

**Comment by andrewscat** [comment]
ok, thank you for help
